name: Build Android

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build on Android (arm64-v8a & x86_64)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-linux-android
          - x86_64-linux-android
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Android NDK and cargo-ndk
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget https://dl.google.com/android/repository/android-ndk-r28b-linux.zip
          unzip -q android-ndk-r28b-linux.zip
          echo "ANDROID_NDK_HOME=$PWD/android-ndk-r28b" >> $GITHUB_ENV
          cargo install cargo-ndk

      - name: Build for Android (aarch64)
        if: matrix.target == 'aarch64-linux-android'
        run: cargo ndk -t arm64-v8a -o ./target build --release

      - name: Build for Android (x86_64)
        if: matrix.target == 'x86_64-linux-android'
        run: cargo ndk -t x86_64 -o ./target build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-release
          path: target/${{ matrix.target }}/release/ 