name: Build Linux

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-x86_64:
    name: Build on Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cross and deps
        run: |
          sudo apt-get update && sudo apt-get install -y libssl-dev libudev-dev
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Build
        run: cross build --release --target x86_64-unknown-linux-gnu
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu-release
          path: target/x86_64-unknown-linux-gnu/release/